/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Main.java
 *
 * Created on Dec 3, 2012, 7:20:28 PM
 */
package bankersproject;

import gui.TransparentPanel;
import java.awt.AWTEvent;
import java.awt.Frame;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.io.IOException;

import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPopupMenu;


/**
 *
 * @author IBM
 */
public class Main extends javax.swing.JFrame implements Runnable,ActionListener {

    /** Creates new form Main */
    TestHarness th;
    private TransparentPanel		topPanel;
          JPopupMenu Pmenu;
               
  JMenuItem menuItem,t1,t2,t3,t4,t5,t6,t7;
    JMenuItem pt1,pt2;

    
    
    public Main() {
        try {
            initComponents();
            
            topPanel = new TransparentPanel();
                    topPanel.setLayout( null );
                    getContentPane().add( topPanel );
            this.setTitle("Banker Projects");
            this.setLocationRelativeTo(null);
            this.imagePanel1.setImage(new ImageIcon(this.getClass().getResource("proj.gif")).getImage());
    
                    
             Pmenu = new JPopupMenu();
          

             
      t1= new JMenuItem("Open File");
        Pmenu.add(t1);
          t2= new JMenuItem("Insert Resources");
        Pmenu.add(t2);

        
      //           pt2= new JMenuItem("RL Transaction Release");
        //     Pmenu.add(pt1);
          //   Pmenu.add(pt2);
                 



     
      //    t4= new JMenuItem("Show Output Text");
        //Pmenu.add(t4);
        
         //     t5= new JMenuItem("New");
       // Pmenu.add(t5);
        
          t6= new JMenuItem("Exit");
        Pmenu.add(t6);

        t1.addActionListener(this);
       t2.addActionListener(this);
        //  pt1.addActionListener(this);
      // pt2.addActionListener(this);
        //  t3.addActionListener(this);
            // t4.addActionListener(this);
          //      t5.addActionListener(this);
                   t6.addActionListener(this);

        
            
         // this.transparentPanel1.setLayout(null);
      topPanel.add(Pmenu);
              enableEvents( AWTEvent.MOUSE_EVENT_MASK );

              
     
              
              
                      Timer timer = new Timer();
MyTimerTask task=new MyTimerTask(this);
    timer.schedule(task, 0, 100);
        } catch (Exception ex) {
      //      Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }

       

    
    }
    
    public void processMouseEvent( MouseEvent event )
	{
		if( event.isPopupTrigger() )
		{
			Pmenu.show( event.getComponent(),
								event.getX(), event.getY() );
                       
		}

		super.processMouseEvent( event );
	}

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imagePanel1 = new gui.ImagePanel();
        transparentPanel1 = new gui.TransparentPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout transparentPanel1Layout = new javax.swing.GroupLayout(transparentPanel1);
        transparentPanel1.setLayout(transparentPanel1Layout);
        transparentPanel1Layout.setHorizontalGroup(
            transparentPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 531, Short.MAX_VALUE)
        );
        transparentPanel1Layout.setVerticalGroup(
            transparentPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 186, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout imagePanel1Layout = new javax.swing.GroupLayout(imagePanel1);
        imagePanel1.setLayout(imagePanel1Layout);
        imagePanel1Layout.setHorizontalGroup(
            imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imagePanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(transparentPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        imagePanel1Layout.setVerticalGroup(
            imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, imagePanel1Layout.createSequentialGroup()
                .addContainerGap(73, Short.MAX_VALUE)
                .addComponent(transparentPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jMenu1.setText("File");

        jMenuItem1.setText("New");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Open");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Exit");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("More");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jMenuItem4.setText("about");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imagePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imagePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
// TODO add your handling code here:
    System.exit(0);
}//GEN-LAST:event_jMenuItem3ActionPerformed

private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
// TODO add your handling code here:
    readFile();
}//GEN-LAST:event_jMenuItem2ActionPerformed

private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
// TODO add your handling code here:
  
}//GEN-LAST:event_jMenu2ActionPerformed

private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
// TODO add your handling code here:
      JOptionPane.showMessageDialog(null, "Ahmad Hammad\n1081443\nMohammad Yeaaqabi\n1090068");
}//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
   /* public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form 
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Main().setVisible(true);
            }
        });
    }*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private gui.ImagePanel imagePanel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private gui.TransparentPanel transparentPanel1;
    // End of variables declaration//GEN-END:variables

    private void readFile() {
        this.th=new TestHarness();
                        JFileChooser jf=new JFileChooser(".");
                jf.showOpenDialog(null);
             

		// get the name of the input file	
   th.inputFile=jf.getSelectedFile();
    }

    @Override
    public void run() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    public void actionPerformed(ActionEvent e) {
        this.repaint();
     	if(e.getSource()==t6){
			System.exit(0);
		}
        
         
        if(e.getSource()==t1){
             
  readFile();
 this.setTitle("File Readed . ");
             
         }
        
         if(e.getSource()==t2){
             
   insertResources();
   
            try {
                this.setState(Frame.ICONIFIED);
                th.main();
            } catch (IOException ex) {
             //   Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            }
             
         }
         
                if(e.getSource()==pt1){
            try {
              
                th.main();
       
            } catch (IOException ex) {
              //  Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            }
             
         }
                                if(e.getSource()==pt2){
             
               try {
                
                th.main();
                 
                
            } catch (IOException ex) {
              //  Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            }
             
         }
                
                       if(e.getSource()==t4){
             
   
             
         }
         
         

    }

    private void insertResources() {
      int rnum=4;
   //   rnum=Integer.parseInt(JOptionPane.showInputDialog("Enter number of resources"));
    //   this.th.numOfResources=rnum;
     this.th.arr=new int[rnum];
      for(int i=0;i<rnum;i++)
      {
     // this.th.arr[i]=Integer.parseInt(JOptionPane.showInputDialog("Enter value of resource "+(i+1)));
      }
      this.th.arr[0]=2;
           this.th.arr[1]=1;
                this.th.arr[2]=0;
                     this.th.arr[3]=0;
    }//
}
